### ISSUE TITLE
won't work

### ISSUE THREAD

**Issue by CooperSwenson** [dpo/atom-brackets-glow#3]
Hey, I can't get this to work for some reason. I've installed and enabled and no cigar.

**Comment by dpo** [comment]
Could you try `⌘-P` and search for "brackets glow: toggle"?

**Comment by dxps** [comment]
Aha! So that was the trick! 😄 
Opening Command Palette using &#x21E7; + &#x2318; + P or using menu Packages > Command Palette > Toggle.

And thank you very much for this beauty!

**Comment by dpo** [comment]
No problem! Thanks.
