### ISSUE TITLE
Not working in Atom 1.12.6

### ISSUE THREAD

**Issue by bunnybooboo** [dpo/atom-brackets-glow#4]
I'm running Atom in Arch and Atom Brackets Glow (0.4.0) is not currently working for me. There's nothing to switch it on, right? Installed a few other Atom packages and they've work as expected.

**Comment by bunnybooboo** [comment]
I'm also having trouble with other Atom cursor related packages in Arch Linux. For example 'neon-selection' (makes selected text field glow) works, but 'glowing-cursor' and 'neon-cursor' do not. Is there perhaps a clash with one-dark-ui theme? EDIT: no even switching to atom-dark has the same bug :/

These are the added packages I have installed: atom-runner, linter, linter-rust, racer, glowing-cursor, linter-jscs, neon-selection, language-rust, linter-jshint, platformio-ide-terminal

If I paste your less code into ~/.atom/styles.less then it works. Something clearly blocking. Also note [deprecation of shadow](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html)

**Comment by dpo** [comment]
Open the command palette and start typing "glow". You should see an option in there to activate this package. Let me know if that works. See also #3.

**Comment by dpo** [comment]
Closing. Please reopen if #3 doesn't work for you.

**Comment by bunnybooboo** [comment]
`Ctrl + Shift + P` did the trick in Linux. Ah wow!! I forgot I had this still installed. Looks superb. Thanks.
